const { one: parseDocument } = require('../../../src/bankOcr');
const stripLastLine = require('../../helpers/stripLastLine');
const test = require('tape');
const { exec } = require('child_process');
const { map, split, compose } = require('ramda');

const NUMBER_OF_TEST_ENTRIES = 30;

const writeTestData = (cb) => exec(`node bin/write-test-data.js one ${NUMBER_OF_TEST_ENTRIES}`, (error, stdout, stderr) => {
	if (error) {
		console.error(`exec error: ${error}`);
		return;
	}

	const makePartOfObject = accountNumber => ({ value: accountNumber, illegible: false });

	compose(cb, map(makePartOfObject), stripLastLine, split('\n'))(stdout);
});

test('Use case one - parses the document and returns the account numbers', (t) => {
	t.plan(NUMBER_OF_TEST_ENTRIES);
	writeTestData(correctAnswers =>
		parseDocument(`${__dirname}/../../data/use-case-one/autogenerated-test-document.txt`, (result) =>
			result.forEach((parsedEntry, idx) => t.deepEqual(parsedEntry, correctAnswers[idx]))
		)
	)
});
